-- Сгенерировано из src/lib/exercise-catalog.ts — не редактируй вручную.
-- Команда пересборки: npm run db:seed

insert into public.exercises (name, muscle_group, equipment, difficulty, is_compound)
values
  ('Жим штанги лёжа', 'chest', 'barbell', 'intermediate', true),
  ('Жим гантелей лёжа', 'chest', 'dumbbell', 'intermediate', true),
  ('Жим гантелей на наклонной скамье', 'chest', 'dumbbell', 'intermediate', true),
  ('Отжимания от пола', 'chest', 'bodyweight', 'beginner', true),
  ('Сведение рук в кроссовере', 'chest', 'cable', 'beginner', false),
  ('Разводка гантелей', 'chest', 'dumbbell', 'beginner', false),
  ('Жим в кроссовере одной рукой', 'chest', 'cable', 'beginner', false),
  ('Становая тяга штанги', 'back', 'barbell', 'intermediate', true),
  ('Тяга штанги в наклоне', 'back', 'barbell', 'intermediate', true),
  ('Подтягивания', 'back', 'bodyweight', 'advanced', true),
  ('Тяга верхнего блока', 'back', 'cable', 'beginner', true),
  ('Тяга гантели в одной руке', 'back', 'dumbbell', 'beginner', true),
  ('Тяга гантели в наклоне с упором', 'back', 'dumbbell', 'beginner', true),
  ('Австралийские подтягивания', 'back', 'bodyweight', 'beginner', true),
  ('Тяга гантели сидя на скамье', 'back', 'dumbbell', 'beginner', false),
  ('Разведение рук в кроссовере', 'back', 'cable', 'beginner', false),
  ('Тяга резинки сидя', 'back', 'band', 'beginner', false),
  ('Присед со штангой', 'legs', 'barbell', 'intermediate', true),
  ('Жим ногами в тренажёре', 'legs', 'machine', 'beginner', true),
  ('Румынская тяга с гантелями', 'legs', 'dumbbell', 'beginner', true),
  ('Выпады с гантелями', 'legs', 'dumbbell', 'beginner', true),
  ('Присед с гантели на одной ноге', 'legs', 'dumbbell', 'intermediate', true),
  ('Разгибания ног в тренажёре', 'legs', 'machine', 'beginner', false),
  ('Сгибания ног лёжа в тренажёре', 'legs', 'machine', 'beginner', false),
  ('Подъёмы на носки стоя', 'legs', 'machine', 'beginner', false),
  ('Взятие гантелей на грудь стоя', 'full_body', 'dumbbell', 'intermediate', true),
  ('Гоблет-присед', 'full_body', 'dumbbell', 'beginner', true),
  ('Жим гантелей над головой сидя', 'full_body', 'dumbbell', 'beginner', true),
  ('Отжимания узким хватом на брусьях', 'full_body', 'bodyweight', 'advanced', true),
  ('Жим штанги стоя', 'shoulders', 'barbell', 'intermediate', true),
  ('Жим гантелей сидя', 'shoulders', 'dumbbell', 'beginner', true),
  ('Тяга штанги к подбородку', 'shoulders', 'barbell', 'beginner', true),
  ('Махи гантелями в стороны', 'shoulders', 'dumbbell', 'beginner', false),
  ('Разводка в кроссовере', 'shoulders', 'cable', 'beginner', false),
  ('Подъём штанги на бицепс стоя', 'arms', 'barbell', 'beginner', false),
  ('Молотки с гантелями', 'arms', 'dumbbell', 'beginner', false),
  ('Сгибания на скамье Скотта', 'arms', 'machine', 'beginner', false),
  ('Разгибания на верхнем блоке', 'arms', 'cable', 'beginner', false),
  ('Французский жим гантелей', 'arms', 'dumbbell', 'intermediate', false),
  ('Планка', 'core', 'bodyweight', 'beginner', false),
  ('Скручивания', 'core', 'bodyweight', 'beginner', false),
  ('Подъёмы ног в висе', 'core', 'bodyweight', 'intermediate', false),
  ('Русские скручивания', 'core', 'dumbbell', 'beginner', true),
  ('Ягодичный мост с резинкой', 'legs', 'band', 'beginner', true),
  ('Разгибания на резинке', 'arms', 'band', 'beginner', false),
  ('Присед с гирей', 'full_body', 'kettlebell', 'intermediate', true)
on conflict (name) do update
  set muscle_group = excluded.muscle_group,
      equipment = excluded.equipment,
      difficulty = excluded.difficulty,
      is_compound = excluded.is_compound;
